 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  salmu:
    # data_dir: ${env.data_dir}/datasets
    data_type: images

    build_info:
      annotations:
        train:
          storage: salmu/annotations/train.json
        val:
          storage: salmu/annotations/val.json
        test:
          storage: salmu/annotations/test.json
      images:
          storage: salmu/images
