model:
  arch: clip

  model_type: ViT-B-16
  load_finetuned: False

  queue_size: 57600
  alpha: 0.4

  negative_all_rank: True

datasets:
  salmu_retrieval: # name of the dataset builder
    vis_processor:
        train:
          name: "clip_image_train"
          image_size: 224
        eval:
          name: "clip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"

run:
  task: retrieval
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-7
  min_lr: 0
  weight_decay: 0.001

  # model specific
  k_test: 256

  output_dir: "./output/clip/retrieval_salmu"

  max_epoch: 10
  log_freq: 1

  # misc
  seed: 42

  amp: False
  resume_ckpt_path: null
  evaluate: False 

  # dataloading
  num_workers: 8
  batch_size_train: 32
  batch_size_eval: 128

  train_splits: ["train"]
  valid_splits: []
  test_splits: ["test"]

  # distribution
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False
